swagger: '2.0'
info:
  title: "Hawkeye API"
  description: "This is a API to manage project Hawkeye"
  version: "1.0.0"
host: "hawkeye.onrender.com"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
paths:

  /notifications:
    post:
      tags:
        - Notifications
      summary: Send a new notification
      description: Allows users or members to send a notification.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                sender_user_id:
                  type: integer
                  nullable: true
                sender_member_id:
                  type: integer
                  nullable: true
              required:
                - message
      responses:
        '201':
          description: Notification sent successfully
        '400':
          description: Invalid input or missing token

  /notifications:
    get:
      tags:
        - Notifications
      summary: Get sent notifications
      description: Retrieves notifications sent by the logged-in user or member.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of sent notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Missing or invalid token
