swagger: '2.0'
info:
  title: "Hawkeye API"
  description: "This is a API to manage project Hawkeye"
  version: "1.0.0"
host: "hawkeye.onrender.com"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
paths: